language: android

sudo: false

before_install:
    - openssl aes-256-cbc -K $encrypted_3e98a6366613_key -iv $encrypted_3e98a6366613_iv -in maven.keystore.gpg.enc -out maven.keystore.gpg -d
    - chmod +x gradlew

jdk:
    - oraclejdk7

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request? $TRAVIS_PULL_REQUEST"
    - echo "Travis tag $TRAVIS_TAG"
    - echo -e "signing.keyId=${signing_keyId}" >> "gradle.properties"
    - echo -e "signing.password=${signing_password}" >> "gradle.properties"
    - echo -e "signing.secretKeyRingFile=../maven.keystore.gpg" >> "gradle.properties"
    - gradle clean assemble test uploadArchives --continue

install:
    - true

notifications:
  email:
    - toxicbakery@gmail.com
